### PR TITLE
Fix repolinter errors

### PR DESCRIPTION
**Pull request by jmertic**
Wait to merge until https://github.com/todogroup/repolinter/pull/186 is merged and released

Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by jfpanisset** [comment]
This is really great stuff, and is helping to flush out the concept of the "template project". A few thoughts:

- Several / most of these files probably deserve a couple of lines of discussion in README.md, that doesn't need to go into this initial PR, but maybe we can create a "list issue" to check them off?
- README.md discusses a simple example of test cases included in a CMake file, this adds a "tests/" directory which is likely correct, but somewhat conflicting with the simple test harness otherwise presented. Could be worth a separate issue to reconcile
- SUPPORT.md is missing a space ("support forthe project")

**Comment by jfpanisset** [comment]
Looks like https://github.com/todogroup/repolinter/pull/186 got merged, is it time to "undraft" this PR and merge it?

**Comment by jmertic** [comment]
@jfpanisset Still waiting for it to be in a release so I'm not pulling off of HEAD.

**Review by jfpanisset — APPROVED** [review]
Looks like https://github.com/todogroup/repolinter/pull/186 went into release 0.10.0 of repolinter, let's merge this branch before the repolinter builds get disabled.

**Pull request merged**
